### ISSUE TITLE
Decide on thresholds and alerts

### ISSUE THREAD

**Issue by esmooov** [newsdev/metrics#16]

**Comment by oldwestaction** [comment]
- [ ] heartbeat responses from huginn
- [ ] disk usage
- [ ] memory & cpu usage
- [ ] error responses / 500s from backends

**Comment by oldwestaction** [comment]
core deck apps & their monitoring needs:
- doc doctor
- listy
- promotron 
- watermark

**Comment by oldwestaction** [comment]
google doc draft of our "monitoring alerts/thresholds plan": https://docs.google.com/document/d/1ZysrgTC4KVj3eDR79wjhNZrnIuPhZKwtXf9UdFyfIZU/edit#
