### ISSUE TITLE
Send an alert from CloudWatch/ NewRelic when a server is down

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#19]
Follow instructions here : 
http://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/

**Comment by 4nj4li** [comment]
hi -- I added the new relic agent to some of our servers last year, and now alerts should pass through cloudwatch to pagerduty, which is a little bit redundant, but gives us many options.  alerts should also post to slack.  also, see below..

[copied from a similar issue]

this is up, but right now only alerts my cellphone. I invited @micaelaroberts @bkoski @esmooov to my trial pagerduty account, where I'm on call on a schedule that rotates between 2 of my email addresses every hour. if you log in, I can add you too!

**Comment by 4nj4li** [comment]
did this without new relic as part of the aws/cloudwatch scripting [here](https://github.com/newsdev/monitoring/commit/13ed9f283ed2deaa33205af1b98e030db6bb56b2).  each dockerized ec2 instance has a status check alarm.  if you search here for 'status,' the alarms are the ones that begin with 'ec2-cluster'
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=inOk
