### ISSUE TITLE
Send an alert when Mongo server is at 80% cpu for more than 15 min

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#20]
Follow instructions here : http://docs.mongolab.com/accounts/#email

**Comment by 4nj4li** [comment]
hello -- I forgot that I'd done this one already, through New Relic, though:

1.  the metric that MongoLab offers in this integration is called 'effective lock,' in percentage units.  I'm assuming this is equivalent to a measure of cpu utilization.
2.  I'm really hoping that the alarm target Mongo hosts are updated automatically in New Relic if/as the hosts' servers/ports change, if they do.  I'll watch for this.

this policy is here in NR:

https://alerts.newrelic.com/accounts/91221/policies/11741
