### ISSUE TITLE
Send an alert when RDS is out of disk space

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#21]
Follow instructions here : 
http://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/

**Comment by 4nj4li** [comment]
this is up, but right now only alerts my cellphone.  I invited @micaelaroberts @bkoski @esmooov to my trial pagerduty account, where I'm on call on a schedule that rotates between 2 of my email addresses every hour.  if you log in, I can add you too!

**Comment by bkoski** [comment]
Just to test it out, I created an alarm here
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=ANY;name=int-rds1%2520low%2520cpu

that triggers when the RDS CPU is <= 50% (ie. all the time).  If you look
in the history, it says that it sent it to pagerduty:

[image: Inline image 1]

But it doesn't seem to have shown up yet:
https://the-new-york-times.pagerduty.com/incidents

is there maybe something wrong w/ the permissions?  Or the config on the
pagerduty side?

**Comment by 4nj4li** [comment]
hi @bkoski, I made you all admins after my initial comment yesterday so it shouldn't be that. on the aws side, I've somehow lost permissions to "view alarms for this account," though scott put me back into the administrators group yesterday. could you re-add? I'll check it out when you do. thank you!

**Comment by 4nj4li** [comment]
also, do you have an idea of when you sent the alert and what it said? I have so many of my own tests that it would really help to know which is potentially yours. thx

**Comment by 4nj4li** [comment]
going to do this + alarms when RDS Server is >80% CPU directly with cloudwatch, no New Relic.

**Comment by 4nj4li** [comment]
these are on production + in AWS, code here https://github.com/newsdev/monitoring/commit/af56ad29df1632f1aafc734b25cca91de0eb827d
