### ISSUE TITLE
Send an alert when ElastiCache instance is at 80% cpu for more than 15 min

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#22]
@bkoski , @buth - what are you thoughts on the time threshold here? I put 15 minutes but it may need to be updated.

**Comment by 4nj4li** [comment]
these should be created [here](https://github.com/newsdev/monitoring/commit/13ed9f283ed2deaa33205af1b98e030db6bb56b2) but I don't see them in the AWS console, and I'm trying to figure out what's wrong.  in the meantime, @buth, I've been creating alarms for all elasticache nodes minus anything that matches 'cooking.'  do you have a better way to get the nodes we want to monitor?  thanks!

**Comment by 4nj4li** [comment]
actually, I didn't check the 80% work in yet.  alas.

**Comment by 4nj4li** [comment]
I guess these do work after all.  they are here:

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=inOk;name=elasticache%253Aprd-elasticache%253A0001%253ACPU-Utilization-80-Percent
