### ISSUE TITLE
Send an alert when host machine is at 90% cpu for more than 15 min

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#24]
@buth , @bkoski , @esmooov , @4nj4li , @oldwestaction - what should the threshold be for this one? Please update if we feel it should not be 15 minutes.

Follow instructions here : 
http://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/

**Comment by 4nj4li** [comment]
this is in place. see here: #31
