### ISSUE TITLE
Send an alert when host machine is at 60% disk full

### ISSUE THREAD

**Issue by micaelaroberts** [newsdev/metrics#25]
per @albertsun - this should be an alert when disk is full at 60% and a ticket should be cut to increase the size.

Follow instructions here : 
http://www.pagerduty.com/docs/guides/aws-cloudwatch-integration-guide/

**Comment by micaelaroberts** [comment]
Lets send a CRITICAL alert when it is at 95% :)

**Comment by 4nj4li** [comment]
@bkoski @micaelaroberts @albertsun re increasing the size, just want to confirm that we want to do this across the board for the cluster- (ie docker) instances, and that you do just mean to apply an autoscaling policy to the instance in question.  is there one that you know of that may be a good one to copy?
https://console.aws.amazon.com/ec2/autoscaling/home?region=us-east-1#LaunchConfigurations:id=m9t-prd-42-web

also, haven't investigated how this works with rds servers, but is that irrelevant now?  will all be on the docker clusters?

thanks!

**Comment by 4nj4li** [comment]
this is mostly in place, minus the size increases.  see here:  https://github.com/newsdev/metrics/issues/31

can we create another ticket for the autoscaling specifics after discussing?
