### ISSUE TITLE
figure out pagerduty account setup

### ISSUE THREAD

**Issue by 4nj4li** [newsdev/metrics#26]
I signed up for a free trial of pagerduty, and it expires in a week!

![screen shot 2015-05-27 at 5 35 39 pm](https://cloud.githubusercontent.com/assets/1473330/7848129/f6db3d14-0496-11e5-90c6-e1a6c2dc8c29.png)

this means that any demo integrations I put together will be gone soon!

I also filled out an infra ticket requesting to be added to the upstairs team's account:
https://jira.nyt.net/browse/INFRA-18701

@esmooov @bkoski @lavallee any thoughts either way?

**Comment by 4nj4li** [comment]
cc @micaelaroberts

**Comment by bkoski** [comment]
Which plan do you think we need to sign up for?  Would the $29/mo plan work?

**Comment by 4nj4li** [comment]
closing because we're going forward with victorops instead. let's reopen if we change our minds, yes @bkoski @esmooov?
