### ISSUE TITLE
Begin to implement the new app performance metrics

### ISSUE THREAD

**Issue by esmooov** [newsdev/metrics#7]
Slow response requests
Error requests (500, 400, 404, 403, etc)
Memory profile of app
App restarts
Reqs/app

**Comment by micaelaroberts** [comment]
This will be a working session with @buth. I will schedule a meeting for Monday/Tuesday.

**Comment by micaelaroberts** [comment]
Assigning to @jeremyjbowers  since he will be working on this with @abstrctn and extending milestone to next week.
